apiVersion: apps/v1
kind: Deployment
metadata:
  name: unsigned-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: unsigned-app
  template:
    metadata:
      labels:
        app: unsigned-app
    spec:
      containers:
        - name: unsigned
          image: public.ecr.aws/docker/library/nginx:latest
